import Head from "next/head";

const Header = (props: any) => {
  const { pageTitle } = props;
  return (
    <Head>
      <title>NextJS Basic | {pageTitle}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default Header;
